// Keys and sizes of the textures generated by the Boot scene
export const TEXTURES = {
    light: 'light',
    glow: 'glow',
    smoke: 'smoke',
    dot: 'dot',
    ring: 'ring',
    bug: 'bug'
} as const;

export const LIGHT_SIZE = 256;      // soft white disc used to erase holes in the darkness
export const RING_SIZE = 128;
export const RING_RADIUS = 60;
