// Offline play and installation (the service worker is generated by vite-plugin-pwa at build time).
// Skipped in development and inside frames: itch.io embeds the game in an iframe on its own domain.
export function registerServiceWorker ()
{
    if (!import.meta.env.PROD || !('serviceWorker' in navigator) || window.top !== window.self) return;

    window.addEventListener('load', () =>
    {
        navigator.serviceWorker.register('./sw.js').catch((error) => console.warn('Offline play is not available:', error));
    });
}
